### PR TITLE
More stuff

### PR DESCRIPTION
**Pull request by rocka0**
Josh can you also add number of seconds left in a day. That will be cool as you can really see it counting down fast.

### CODE REVIEW

**Comment by raichur** [comment]
I agree that it will count down fast, but I already have waking hours left in a day, which is more useful than seconds.

**Comment by rocka0** [comment]
k then thanks

**Comment by raichur** [comment]
I'll possibly refactor the code and style it better this evening.

**Comment by rocka0** [comment]
dats fine and nice to talk to you again

**Comment by raichur** [comment]
Nice talking to you too.

**Comment by rocka0** [comment]
k then instead of gmail lets talk here and btw im learning javascript. If i need help, i can ask u right?

**Comment by rocka0** [comment]
and also whats the use of a gh-pages branch when you have a master branch>?

**Comment by raichur** [comment]
The gh-pages branch allows you to host websites straight from your repo. Try uploading an `index.html` file with some content in a repo with `gh-pages` branch as default, then visit rocka0.github.io/_REPO_NAME_. It's pretty convenient.

**Comment by rocka0** [comment]
ohh i see

**Comment by rocka0** [comment]
ok

**Comment by rocka0** [comment]
got it gonna get my own domain man soo cooolll!!!!!

**Comment by rocka0** [comment]
its not working i waited 5 mins and it didnt come!

**Comment by raichur** [comment]
I was talking about a project page `/repo`, but you created a user page. It has good documentation: https://pages.github.com/

**Comment by rocka0** [comment]
man i didnt understand :(

**Comment by rocka0** [comment]
got it you meant the other tab in the documentation!!

**Comment by raichur** [comment]
Yup, that's what I meant.

**Comment by rocka0** [comment]
man can you tell me how to do it

**Comment by rocka0** [comment]
i made the repo but its not working so i deleted it its just not publishing

**Comment by rocka0** [comment]
i made a repo called website can u tell me how to publish it and btw the new motivation looks dddddddaaaaaaaaaaaaaammmmmmmmnnnnnn cool!!!!!!!!!!!! :smile :smile:

**Comment by rocka0** [comment]
i request you to make a repo for me which just has an index.html file which says hello world. The page should be stored at tushchen.com. Just this much, ill develop on it later pls pls pls pls pls man pls

**Comment by rocka0** [comment]
Hello josh are you there??

**Comment by raichur** [comment]
Could you give me your email address?

**Comment by rocka0** [comment]
sure its tusky2002@gmail.com

**Comment by rocka0** [comment]
josh i see you are online how are you?

**Comment by rocka0** [comment]
i need to talk to you

**Comment by rocka0** [comment]
please respond

**Comment by raichur** [comment]
Did you check your email?

**Comment by rocka0** [comment]
didnt though ill check it this weekend

**Pull request closed without merging**
